<?php

return [
    '94230d61-cd9d-5d26-88b6-ea3ccdf86b3a' => [
        'With every drop of water you drink, every breath you take, you\'re connected to the sea. No matter where on Earth you live. Most of the oxygen in the atmosphere is generated by the sea.',
        'Sylvia Earle',
    ],
    'd4012e6e-13fa-53e5-a99c-5fed1484259e' => [
        'Young people need the hands-on training that comes with a summer job. They need to know how to dress for success and nail job interviews. But most of all, they need mentorship, guidance, and inspiration.',
        'Hilda Solis',
    ],
    '3f3cf6c7-3af7-5936-89b7-d44cedbd176f' => [
        'Don\'t cry because it\'s over. Smile because it happened.',
        'Dr. Seuss',
    ],
    '5a728b4a-e718-58b6-92dd-e9e2fa60def5' => [
        'If you\'re in a bad situation, don\'t worry it\'ll change. If you\'re in a good situation, don\'t worry it\'ll change.',
        'John Simone',
    ],
    'c2b0046d-2ca4-539f-8c93-002828887891' => [
        'The most important thing we can do is inspire young minds and to advance the kind of science, math and technology education that will help youngsters take us to the next phase of space travel.',
        'John Glenn',
    ],
    '580c644c-78cd-5e98-8ed2-1ef176414eb3' => [
        'Imagination is more important than knowledge. For while knowledge defines all we currently know and understand, imagination points to all we might yet discover and create.',
        'Albert Einstein',
    ],
    '75073295-08da-5295-b76e-67b7e7910b31' => [
        'My definition of success is to live your life in a way that causes you to feel a ton of pleasure and very little pain - and because of your lifestyle, have the people around you feel a lot more pleasure than they do pain.',
        'Tony Robbins',
    ],
    '66f9bd46-5c7a-5a3f-865e-f2e78cd9d52e' => [
        'I travel Europe every couple of weeks. I just came back from London, Holland and Denmark. Every nation on this planet has its issues with race, and I am not sure if everyone has figured out how to deal with it.',
        'Montel Williams',
    ],
    '831e68ed-28b5-549f-b5d4-c1405089e8e8' => [
        'To become an able and successful man in any profession, three things are necessary, nature, study and practice.',
        'Henry Ward Beecher',
    ],
    '41a3ddc8-bd2c-55a0-82a3-19004ee3d141' => [
        'What we think determines what happens to us, so if we want to change our lives, we need to stretch our minds.',
        'Chris Kyle',
    ],
    '4cc54396-d1ca-5928-a58a-8a078e5ef07f' => [
        'Success is the most important to many, to me it\'s just a bonus.',
        'Lucas Grabeel',
    ],
    '249174a0-1d0d-5a0f-afd4-7e47bd9231f8' => [
        'Is it right to probe so deeply into Nature\'s secrets? The question must here be raised whether it will benefit mankind, or whether the knowledge will be harmful.',
        'Pierre Curie',
    ],
    '6729cbaf-6df8-57a7-a2f9-8a3d249975c5' => [
        'Success is not the absence of failure; it\'s the persistence through failure.',
        'Aisha Tyler',
    ],
    'c5918ab8-83c2-5b72-9290-19b6d1c53f44' => [
        'Music became a healer for me. And I learned to listen with all my being. I found that it could wipe away all the emotions of fear and confusion relating to my family.',
        'Eric Clapton',
    ],
    '0c654a9f-5b0a-5e7d-ac8a-42273f371a76' => [
        'Managers in all too many American companies do not achieve the desired results because nobody makes them do it.',
        'Harold S. Geneen',
    ],
    'c632b0cc-1cd5-50ab-89c0-37949b30bf64' => [
        'People are the key to success or extraordinary success.',
        'Azim Premji',
    ],
    '9da75f59-c1d9-57be-841f-a8d92ec5035f' => [
        'Belief is so important in everything. You need to believe in magic. You need to believe in yourself. You need to believe in your family.',
        'Edward Kitsis',
    ],
    '7863923a-1660-5e84-82d6-0834a5967efd' => [
        'Frost is the greatest artist in our clime - he paints in nature and describes in rime.',
        'Thomas Hood',
    ],
    'a6608bf2-e57f-574b-b1b5-0a5cf542aee8' => [
        'If a little dreaming is dangerous, the cure for it is not to dream less but to dream more, to dream all the time.',
        'Marcel Proust',
    ],
    '70c65ff6-fa12-5739-9c55-41f14b29e28d' => [
        'I think we should all be tolerant of each other and embrace each others\' strengths and differences and uniqueness and beauty.',
        'Martina McBride',
    ],
    '93baff11-8df2-527d-a6b9-87af5908cee0' => [
        'Camping is nature\'s way of promoting the motel business.',
        'Dave Barry',
    ],
    'f9f22947-10a9-5866-a818-f3f4f278608d' => [
        'The family farm is the foundation for who we are as a Commonwealth. And for over a century, the family farm in Kentucky has centered around one crop: tobacco.',
        'Jim Bunning',
    ],
    '35555fd4-3043-50f5-a849-cc0972441cfd' => [
        'Today, people idolize athletes and celebrities - and yes, highly successful and visionary business people like Bill Gates or Steve Jobs, but not the innovators who perhaps have not seen such high-flying levels of success. Can anyone name the inventors of GPS, which has such a huge impact on our lives today?',
        'Naveen Jain',
    ],
    '9f0d5fd0-288f-5d59-ba80-9e0c54db5653' => [
        'I think what it takes to succeed remains the same. You have to have a real love of your sport to carry you through all the bad times, you still want to go ski even when things aren\'t working. You must have a commitment to work hard and to never give up.',
        'Nancy Greene',
    ],
    '6830f23e-6467-59dc-aa1d-599581d186dc' => [
        'People who don\'t travel cannot have a global view, all they see is what\'s in front of them. Those people cannot accept new things because all they know is where they live.',
        'Martin Yan',
    ],
    'b47ada99-b9ff-5e03-a153-f0d9d4f7e16c' => [
        'Try and fail, but don\'t fail to try.',
        'Stephen Kaggwa',
    ],
    'ccfd5f8e-8cec-582e-ac6c-f165b0518587' => [
        'First of all, I try to be a positive role model.',
        'Caitlyn Jenner',
    ],
    '0ed7df40-7ed9-5025-b85f-3b3f48f8754c' => [
        'The world judge of men by their ability in their profession, and we judge of ourselves by the same test: for it is on that on which our success in life depends.',
        'William Hazlitt',
    ],
    '077300f5-45a1-5a72-8a80-87012b67d5ec' => [
        'My dream is of a place and a time where America will once again be seen as the last best hope of earth.',
        'Abraham Lincoln',
    ],
    '1e922302-0702-5529-9889-adbb00ce7a7c' => [
        'Alzheimer\'s, Parkinson\'s, brain and spinal cord disorders, diabetes, cancer, at least 58 diseases could potentially be cured through stem cell research, diseases that touch every family in America and in the world.',
        'Rosa DeLauro',
    ],
    'd8d19500-7b97-543f-b79e-b54da6fae1da' => [
        'There was a great strain in our family because my father didn\'t want anything to do with me. He was happy to see my brother and sister, but not me. I don\'t know why. Maybe it was shame. I don\'t know. But he never wanted anything to do with me. That rejection was terribly hurtful and it went on for years.',
        'Carol Vorderman',
    ],
    'ce399b86-e579-586a-bcbc-20c738f951ee' => [
        'To be what we are, and to become what we are capable of becoming, is the only end of life.',
        'Robert Stevenson',
    ],
    '5add9366-0f20-507b-8d75-63b235ed0c83' => [
        'Of course, the most important factor of all for long life is a good family. When a person goes home with the wife or the kids giving him endless headaches, then it\'s hard for that person to enjoy a long life. I am very fortunate, because my wife Elizabeth and my obedient children are very good; they have given me happiness.',
        'John Gokongwei',
    ],
    '23e3434f-2948-55dd-a5f4-d0d494c5b3a5' => [
        'Without hard work, nothing grows but weeds.',
        'Gordon B. Hinckley',
    ],
    '75178312-307f-5c26-a1ea-77f1e721ed4e' => [
        'Nature provides exceptions to every rule.',
        'Margaret Fuller',
    ],
    'f7a9298a-67e4-54ce-8153-6e4f75a1d1c6' => [
        'Do not look for approval except for the consciousness of doing your best.',
        'Andrew Carnegie',
    ],
    '079d0fc9-ec69-57fb-b0d8-bf6ab04ce7b5' => [
        'When I had money in the past, I would always travel rather than spend it on big apartments or cars. And I still feel exactly the same way.',
        'Robin Wright',
    ],
    'e786156b-afb9-5d76-a7ff-f04b29ace048' => [
        'I\'ve always believed that you can think positive just as well as you can think negative.',
        'James A. Baldwin',
    ],
    '9b4a5971-dcda-5046-886a-3d7a252f6582' => [
        'Working together in concert more smoothly not only helps us move more quickly; it changes the nature of what we can undertake. When we have the confidence that we can orchestrate the group effort required to realize them, we dare bigger dreams.',
        'Justin Rosenstein',
    ],
    'd96cc180-6880-5dab-ada2-5c1d0140add4' => [
        'I want to be a little more dramatic nowadays. I definitely want something big and funny, but I look for things that can just have people see me in a different light and let me mature as both an entertainer and an actor and a comedian.',
        'Cedric the Entertainer',
    ],
    '126db1c4-0dae-54dd-988c-8f5732f79251' => [
        'That\'s my main flaw: I always think authority figures or my boss is going to think something I do is funny. And usually they don\'t.',
        'Jimmy Kimmel',
    ],
    'c8b3774c-3438-5d7e-80b8-f3f7b5f3ae75' => [
        'I am against nature. I don\'t dig nature at all. I think nature is very unnatural. I think the truly natural things are dreams, which nature can\'t touch with decay.',
        'Bob Dylan',
    ],
    'c7680e20-1d4e-535f-8934-8a2f9f3c325f' => [
        'Comfort is the enemy of achievement.',
        'Farrah Gray',
    ],
    '532eb7e0-35e1-5fa1-8bae-155a5ceabf94' => [
        'I\'d like to grow up and be beautiful. I know it doesn\'t matter, but it doesn\'t hurt.',
        'Kirsten Dunst',
    ],
    '77bc2661-822d-5c4e-a6b6-173c7f427105' => [
        'It is good to dream big but your dreams will never see the light of day if you sleep big too.',
        'Anonymous',
    ],
    '8dbf5444-2e64-589e-8c71-315efc878da8' => [
        'The best preparation for good work tomorrow is to do good work today.',
        'Elbert Hubbard',
    ],
    '50af0eb4-c388-553e-85c5-c24b73688459' => [
        'Heat cannot be separated from fire, or beauty from The Eternal.',
        'Dante Alighieri',
    ],
    '4a4b6c4f-15bd-505c-a7e3-92c7f712c579' => [
        'I knew from the first moment I picked up a camera, on my first school assignment, what I wanted to do for the rest of my life. I was going to find a way to travel the world and tell the stories of the people I met through photographs.',
        'Mary Ellen Mark',
    ],
    'c9e93cf4-77db-5b22-bb55-7662cd56ac7d' => [
        'The world is round and the place which may seem like the end may also be the beginning.',
        'Ivy Baker Priest',
    ],
    'f3aab0db-a01c-5388-93ae-c5ec67130216' => [
        'Decide that you want it more than you are afraid of it.',
        'Bill Cosby',
    ],
];
