<?php

return [
    '16be6728-d62e-5036-b08b-a05589858d38' => [
        'I hope that my family will continue in another thousand years.',
        'Frederik, Crown Prince of Denmark',
    ],
    'be64acc8-0cc1-5e65-9f71-c5efd1e9973b' => [
        'The measure of a man is what he does with power.',
        'Plato',
    ],
    '57082d3f-597b-50e5-9f85-41e43a259511' => [
        'So many of our young women today, they\'re growing up without a father, but they\'re still thirsty for that and desiring positive male love.',
        'Hill Harper',
    ],
    '53a564ef-f66d-51b5-98e7-4033bbb6b154' => [
        'We try to make the name longer and longer every year. First, it was \'Larry the Cable Guy\'s Christmas Spectacular.\' Then it was \'It\'s a Very Larry Christmas.\' Now it\'s \'Larry the Cable Guy\'s Hula-palooza Christmas Luau.\' I\'ll tell you what it is: It\'s funny. That\'s what it is. Who cares what the name of it is? It is a funny special.',
        'Larry the Cable Guy',
    ],
    '5a189467-5ff0-509f-95df-fc0b362cff31' => [
        'The bad news is time flies. The good news is you\'re the pilot.',
        'Michael Atshuler',
    ],
    '78af3eef-0415-5875-97ed-0c29f041db57' => [
        'One of my favorites is one called \'Rory\'s Radio\' that I wrote about my brother Jeff\'s best friend growing up - his name was Rory Dunigan. I dedicated my first record to my brother, who got killed in a car accident in 1999, and I really didn\'t have any songs on the first album about him, nothing on a personal note.',
        'Ashton Shepherd',
    ],
    '67fbd2cf-b9b7-5dba-9d5f-223dddd155e5' => [
        'To you wives who are constantly complaining and see only the dark side of life, and feel that you are unloved and unwanted, look into your own hearts and minds. If there is something wrong, turn about. Put a smile on your faces. Make yourselves more attractive. Brighten your outlook.',
        'Gordon B. Hinckley',
    ],
    'a188997b-54a6-519a-bd8b-0749fc874815' => [
        'Traveling around the country, meeting fans and hearing their stories in person and on my radio show has reenergized my commitment to creating honest and inspirational content that not only serves my own creative purposes but can help and touch others as well.',
        'Nikki Sixx',
    ],
    'f0c9c181-9924-5972-bb81-f42cb8f8e661' => [
        'People come into your lives who you have a good time with, and time goes by and you still have a good time with them and you do stupid stuff with them. To me, that\'s life.',
        'Danny DeVito',
    ],
    '9d3f7257-b3fb-56e3-adf3-3eda4091d3df' => [
        'I want to have fun. It\'s a beautiful life. You learn, you win, you lose, but you get up.',
        'John Wooden',
    ],
    '9320e5fd-96f4-58e7-9d88-c939ce4a3ab9' => [
        'All the great artists had their dark sides. Look at Amy Winehouse or anyone who has achieved a certain level of success. Even Adele, and the people that you wouldn\'t put in the same category as a gangster rapper. These women have exposed their vulnerabilities, demons, and things that have hurt them.',
        'Kat Graham',
    ],
    'e94f92ac-00f4-5474-b0dd-c52bb87cd336' => [
        'Even Napoleon had his Watergate.',
        'Yogi Berra',
    ],
    '7c5128e7-ccf7-5c1f-8c6d-a2375de54573' => [
        'Everything has been figured out, except how to live.',
        'Caitlyn Jenner',
    ],
    'f5bf79cb-b94c-5f74-b66b-04ce8fad9375' => [
        'The flower is the poetry of reproduction. It is an example of the eternal seductiveness of life.',
        'Jean Giraudoux',
    ],
    '6ae89442-a007-50f2-8d71-cb108ee6aa48' => [
        'The ultimate aim of the ego is not to see something, but to be something.',
        'Muhammad Iqbal',
    ],
    'ede263a9-3232-5bc4-876f-9d8774062905' => [
        'One of the signs of a bad coworker is a pattern of persistent undermining - intentionally hindering a colleague\'s success, reputation, or relationships.',
        'Adam Grant',
    ],
    '93d97ca0-5296-5624-8064-7451d7773e35' => [
        'It is precisely the purpose of the public opinion generated by the press to make the public incapable of judging, to insinuate into it the attitude of someone irresponsible, uninformed.',
        'Walter Benjamin',
    ],
    '42a2173b-c05c-53fc-97f5-b0bf036c317c' => [
        'For in the true nature of things, if we rightly consider, every green tree is far more glorious than if it were made of gold and silver.',
        'Martin Luther',
    ],
    'c8a60221-1811-58a1-9373-44ce9b76130b' => [
        'Things are never quite as scary when you\'ve got a best friend.',
        'Bill Watterson',
    ],
    'c36f0e90-1b91-5560-a493-624c822c164a' => [
        'Courage is the discovery that you may not win, and trying when you know you can lose.',
        'Unknown',
    ],
    '97966c6f-946d-5388-8ccd-8fd0cb5ed610' => [
        'The thing is that love gives us a ringside seat on somebody else\'s flaws, so of course you\'re gonna spot some things that kinda need to be mentioned. But often the romantic view is to say, \'If you loved me, you wouldn\'t criticise me.\' Actually, true love is often about trying to teach someone how to be the best version of themselves.',
        'Alain de Botton',
    ],
    '76c47b4b-7de2-5071-859e-2af3d65c4596' => [
        'Success is an absurd, erratic thing. She arrives when one least expects her and after she has come may depart again almost because of a whim.',
        'Alice Foote MacDougall',
    ],
    '19a22d95-c326-5c78-992f-a34943394396' => [
        'America needs to understand Islam, because this is the one religion that erases from its society the race problem. Throughout my travels in the Muslim world, I have met, talked to, even eaten with people who in America would have been considered \'white,\' but the \'white\' attitude had been removed from their minds by the religion of Islam.',
        'Malcolm X',
    ],
    '75b494c4-2fe9-5109-82a2-2a17c417be00' => [
        'I try and have a relaxed attitude and stay quite switched off until about an hour before kick-off.',
        'Roy Keane',
    ],
    '58c34900-1286-52c8-8fa8-d94cc5ac5de0' => [
        'Hollywood needs to recognise all shades of African American beauty.',
        'Gabrielle Union',
    ],
    '4564cf2b-34fe-5884-8ff0-95236aa5165a' => [
        'Life hands us a lot of hard choices, and other people can help us more than we might realize. We often think we should make important decisions using just our own internal resources. What are the pros and cons? What does my gut tell me? But often we have friends and family who know us in ways we don\'t know ourselves.',
        'Sheena Iyengar',
    ],
    'f43e616f-5292-575c-9c6f-6868f9e7b61c' => [
        'Every one has her own love life. Every one has a dream to get a perfect life partner. But this is not so easy in real life. In fact, one doesn\'t love; it happens.',
        'Ariana Grande',
    ],
    '1fcf8de4-1ce2-55d5-ac12-341fe0eab138' => [
        'Strong people make as many mistakes as weak people. Difference is that strong people admit their mistakes, laugh at them, learn from them. That is how they become strong.',
        'Richard Needham',
    ],
    '03f1a650-8555-5dbd-a06c-7bfad204e119' => [
        'Colors are the smiles of nature.',
        'Leigh Hunt',
    ],
    'e55433fb-6e3d-54aa-9758-e4deedaf7ac0' => [
        'Coca-Cola is the only business in the world where no matter which country or town or village you are in, if someone asks what do you do, and you say you work for Coca-Cola, you never have to answer the question, \'What is that?\'',
        'Muhtar Kent',
    ],
    'c252bd04-887b-5964-8ed4-9a35d1d60e6f' => [
        'Never say there is nothing beautiful in the world any more. There is always something to make you wonder in the shape of a tree, the trembling of a leaf.',
        'Albert Schweitzer',
    ],
    '4b1c7198-d0de-5c04-82a4-4ae9743fd05c' => [
        'Bad things do happen; how I respond to them defines my character and the quality of my life. I can choose to sit in perpetual sadness, immobilized by the gravity of my loss, or I can choose to rise from the pain and treasure the most precious gift I have - life itself.',
        'Johann Wolfgang von Goethe',
    ],
    'ec196b77-f5c8-5f2c-80c4-091c1dcc80ec' => [
        'A good boss makes his men realize they have more ability than they think they have so that they consistently do better work than they thought they could.',
        'Charles Erwin Wilson',
    ],
    'd89ada99-fca6-5a05-8f04-1aebca7f32fe' => [
        'We live in deeds, not years; in thoughts, not breaths; in feelings, not in figures on a dial. We should count time by heart throbs. He most lives who thinks most, feels the noblest, acts the best.',
        'Aristotle',
    ],
    '25248b8f-661b-5ee2-bcbb-e0091f498081' => [
        'The ultimate value of life depends upon awareness and the power of contemplation rather than upon mere survival.',
        'Cindy Morgan',
    ],
    'd86679de-7617-5300-b1bb-03e5910553d9' => [
        'Good leaders need a positive agenda, not just an agenda of dealing with crisis.',
        'Michael Porter',
    ],
    '4b425a3b-ae43-5b31-a523-2f761f1a79c2' => [
        'It can\'t be spring if your heart is filled with past failures.',
        'Byron Pulsifer',
    ],
    'e103002f-a4e3-5326-9143-aeb7b60b7e1b' => [
        'People who urge you to be realistic generally want you to accept their version of reality.',
        'Unknown',
    ],
    '7b3a3a1a-8e8c-5c28-8a17-2a10ebaadd5a' => [
        'Even with all the negativeness of the whole social media thing, I still think it\'s leaps and bounds more positive.',
        'Luke Bryan',
    ],
    '0ad67ecd-ca87-59f9-bbfc-12a090b29481' => [
        'Careers, like rockets, don\'t always take off on time. The trick is to always keep the engine running.',
        'Gary Sinise',
    ],
    'b041bece-f994-5ddd-85ca-e265a4ab5edc' => [
        'Please, no matter how we advance technologically, please don\'t abandon the book. There is nothing in our material world more beautiful than the book.',
        'Patti Smith',
    ],
    '9d3a064f-89fa-5272-94e6-e0bee354159f' => [
        'When a man tells you that he got rich through hard work, ask him: \'Whose?\'',
        'Don Marquis',
    ],
    '820e5792-cfc6-56dc-a640-9f28cfc9e9c0' => [
        'Arriving at one goal is the starting point to another.',
        'John Dewey',
    ],
    'ca52eadb-94fd-5690-8ae4-51bf9361b62b' => [
        'Everything happens to everybody sooner or later if there is time enough.',
        'George Bernard Shaw',
    ],
    'df6c1797-8106-5dc9-82eb-b672a88319cb' => [
        'I\'ve decided to run for the U.S. Senate because I believe Wisconsin families need a senator who will work hard to deliver results for the middle class - a leader with the courage to do what\'s right, no matter how tough the odds or how powerful the special interests we have to fight.',
        'Tammy Baldwin',
    ],
    '65822e0d-bb82-5f4c-be65-5aea5fda8701' => [
        'Step by step and the thing is done.',
        'Charles Atlas',
    ],
    '61cf051c-21b3-520b-8edb-3786837d7cc5' => [
        'Do you know, it\'s funny, but I never thought of being blind as a disadvantage, and I never thought of being black as a disadvantage.',
        'Stevie Wonder',
    ],
    'd147f741-3a0e-5aa1-899a-63ddac065143' => [
        'Women in particular need to keep an eye on their physical and mental health, because if we\'re scurrying to and from appointments and errands, we don\'t have a lot of time to take care of ourselves. We need to do a better job of putting ourselves higher on our own \'to do\' list.',
        'Michelle Obama',
    ],
    '1f6aa686-bd12-54b3-b08c-5c87df2a68c4' => [
        'Life is too short to be doing work that doesn\'t make you feel happy and fulfilled. I\'d rather wait for the right project, as opposed to just taking whatever is handed to me.',
        'Amanda Crew',
    ],
    '1ba905ff-eef2-57fd-aa2a-8b6aeaa276e5' => [
        'Life is the art of drawing without an eraser.',
        'Walt Disney',
    ],
];
