<?php

declare(strict_types=1);

return [
    '17d65c56-7dca-553a-a632-78d36a7adbaf' => [
        'Just like hair frames our face, brows frame our eyes. I see so much potential in harmonized beauty whenever I see a woman who\'s not filling in her brows, and I just want to go in with my brow pencil and just be like, \'Filling in eyebrows, OK, done - look in the mirror and be inspired.\' That\'s one of my pet peeves, but beauty is subjective.',
        'Michelle Phan',
    ],
    '78cae4e2-ffd1-5755-987a-e3af6212c14f' => [
        'The funny thing about insane people is that it is kind of the opposite of being a celebrity. Nobody envies you.',
        'Robert M. Pirsig',
    ],
    'cb8a1d4e-6dca-59ff-9368-9cce7adaa216' => [
        'I\'m homesick all the time. I miss my animals. I miss my family. I miss my friends.',
        'Brittany Howard',
    ],
    'ab7e8e6c-5d93-5157-9aee-e7a339033c1f' => [
        'Life is a series of punches. It presents a lot of challenges. It presents a lot of hardship, but the people that are able to take those punches and able to move forward are the ones that really do have a lot of success and have a lot of joy in their life and have a lot of stories to tell, too.',
        'Josh Turner',
    ],
    'efdd3c2b-0250-5f9a-a9eb-2372a0b00ceb' => [
        'Eyebrows are really important because they structure the face. In school it was funny because I was always the one walking around with tweezers plucking my girlfriends\' eyebrows. I was really good; eyebrow tweezing runs in my family - my mother used to do mine, and I picked it up.',
        'Rita Ora',
    ],
    '9d0d045e-d740-5933-b679-e5e37d7e20a6' => [
        'I was born with an extremely negative attitude. I was the kid who wouldn\'t smile in Christmas photos, was a poor sport, and hated a lot of things. I eventually grew out of my negativity when I matured.',
        'Colton Haynes',
    ],
    '9f4f1b3b-2328-5212-8326-ef7ced3d2a05' => [
        'I eat every two hours. I sleep for eight hours. I have lots of water. I pray to keep calm. Most importantly, I have a smile on my face.',
        'Vidya Balan',
    ],
    '9938037e-0ccd-5da8-9750-4c26b115f739' => [
        'Dates that come around every year help us measure progress in our lives. One annual event, New Year\'s Day, is a time of reflection and resolution.',
        'Joseph B. Wirthlin',
    ],
    '8650258c-2b7e-558c-910b-1985517c5d4f' => [
        'Each day provides its own gifts.',
        'Marcus Aurelius',
    ],
    '2270e77b-052e-5bc3-bd4d-1d13b280013f' => [
        'I\'m doing a pilot for Comedy Central with the band Steel Panther. They\'re faux heavy metal. They started as kind of a tribute band out here, or a cover band, and they\'re funny guys, and they just sort of morphed into their own thing.',
        'Brian Posehn',
    ],
    'e6533a20-ead8-59b5-b9c9-6f5588a0c69b' => [
        'We all have goals: We want to matter. We want to be important. We want to have freedom and power to pursue our creative work. We want respect from our peers and recognition for our accomplishments. Not out of vanity or selfishness, but of an earnest desire to fulfill our personal potential.',
        'Ryan Holiday',
    ],
    '77988d2c-94f1-588e-a13d-9234d0d4341b' => [
        'The man who interprets Nature is always held in great honor.',
        'Zora Neale Hurston',
    ],
    '9fe1df6e-e92a-56d6-b379-9d74f68e20d1' => [
        'Trust in dreams, for in them is hidden the gate to eternity.',
        'Khalil Gibran',
    ],
    '93d97ca0-5296-5624-8064-7451d7773e35' => [
        'It is precisely the purpose of the public opinion generated by the press to make the public incapable of judging, to insinuate into it the attitude of someone irresponsible, uninformed.',
        'Walter Benjamin',
    ],
    'c57cebe3-bda9-5236-ab1f-e28b6c5d6caa' => [
        'To know even one life has breathed easier because you have lived. This is to have succeeded.',
        'Bessie Anderson Stanley',
    ],
    '18a7adba-0f7b-58d9-9b80-d09d1848db53' => [
        'A lot of America is kind of done. People have been making films about it for 100 years. Everything to me feels used up. But Jo-Burg feels unbelievably inspirational to me.',
        'Neill Blomkamp',
    ],
    'b9e7fbaf-60bf-5e9b-be12-6ec96fb32f95' => [
        'It is better to be hated for what you are than to be loved for what you are not.',
        "Andr\u{e9} Gide",
    ],
    '5f5ed5b3-dd0f-5403-b17c-d1aa91ad3340' => [
        'Because I have work to care about, it is possible that I may be less difficult to get along with than other women when the double chins start to form.',
        'Gloria Steinem',
    ],
    'f7f26c65-3fe4-5c95-8394-9569c2babc32' => [
        'We do not celebrate people who have made success out of serious hard work.',
        'Iain Duncan Smith',
    ],
    '3ec448e1-e1e5-5da5-8162-33ec8aeaf5d8' => [
        'No one\'s going to be able to operate without a grounding in the basic sciences. Language would be helpful, although English is becoming increasingly international. And travel. You have to have a global attitude.',
        'Rupert Murdoch',
    ],
    '3e7ebd6d-9765-5ebf-970d-c32634c5dfff' => [
        'Don\'t worry if people don\'t like you. Most people are struggling to like themselves.',
        'Unknown',
    ],
    'af320faa-978a-5e93-bb3e-444c93e22a38' => [
        'Americans have always had an ambivalent attitude toward intelligence. When they feel threatened, they want a lot of it, and when they don\'t, they regard the whole thing as somewhat immoral.',
        'Vernon A. Walters',
    ],
    '1f4d86d3-16b6-5c71-9289-8023c03ec0d5' => [
        'Success usually comes to those who are too busy to be looking for it.',
        'Henry David Thoreau',
    ],
    'bf6e455c-5b92-5b9a-9c43-1613a745df53' => [
        'Our situation today shows that beauty demands for itself at least as much courage and decision as do truth and goodness, and she will not allow herself to be separated and banned from her two sisters without taking them along with herself in an act of mysterious vengeance.',
        'Hans Urs von Balthasar',
    ],
    'd8d19500-7b97-543f-b79e-b54da6fae1da' => [
        'There was a great strain in our family because my father didn\'t want anything to do with me. He was happy to see my brother and sister, but not me. I don\'t know why. Maybe it was shame. I don\'t know. But he never wanted anything to do with me. That rejection was terribly hurtful and it went on for years.',
        'Carol Vorderman',
    ],
    '0a60361a-0fc3-521d-a9d0-ecb17fcb87cc' => [
        'The survival of liberty in our land increasingly depends on the success of liberty in other lands. The best hope for peace in our world is the expansion of freedom in all the world.',
        'Bill Frist',
    ],
    '846957c5-441b-5e65-9b09-caeed58608f5' => [
        'People like her because she\'s like a breath of fresh air. Because in the fifth book it gets so dark and Harry\'s always cross and then every time Luna comes in all the tension goes and she makes you laugh because she\'s so funny and really honest. I don\'t know how much I\'m like her, there are some similarities but I\'m more determined than her.',
        'Evanna Lynch',
    ],
    '62064450-9b5e-5572-9ead-be284591cb4f' => [
        'I think \'Heroes of Cosplay\' will show a lot of the positive things, like how much effort it takes to make a costume. These people on the show aren\'t taking shortcuts. As long as that effort gets through to the viewers, we will be inspirational. Then there will be people who watch the show that want to get in and hands-on make outfits.',
        'Yaya Han',
    ],
    'fb964e9c-788a-59c5-ad82-ff7b5ed3fafc' => [
        'Happiness does not come about only due to external circumstances; it mainly derives from inner attitudes.',
        'Dalai Lama',
    ],
    '75333095-d514-5a91-92d2-a08ccb4a7bc8' => [
        'Basically, when you get to my age, you\'ll really measure your success in life by how many of the people you want to have love you actually do love you.',
        'Warren Buffett',
    ],
    '2fe56710-79cd-5820-acae-9b8cfb87334a' => [
        'Hope is not just... out in the sky, or accepting the facts or reality. Hope is having optimistic, positive expectations.',
        'Craig Sager',
    ],
    'fc3df727-6eb8-5ab1-936e-59ff51b13e12' => [
        'To be candid, some people have given positive thinking a bad name. I can\'t stand to hear some gung-ho individual say that with positive thinking you can just do \'anything.\' If you think about that one for a moment, you recognize the absurdity of it.',
        'Zig Ziglar',
    ],
    '186ac4c6-84b5-54d5-8fa1-56d249c924d7' => [
        'Everything in life is luck.',
        'Jennifer Love Hewitt',
    ],
    '2d080d09-28d2-5697-89a6-f0203442776f' => [
        'Luxury is the wolf at the door and its fangs are the vanities and conceits germinated by success. When an artist learns this, he knows where the danger is.',
        'Tennessee Williams',
    ],
    '4734f682-87a4-5964-b3d5-556ea03a8c5e' => [
        'I\'m opening up my heart to the idea of dating. It\'s funny - my friends would always come to me for romantic advice. I know nothing, and things have changed since I was dating in high school! I\'m really trying hard to spend this time working on myself.',
        'Olivia Wilde',
    ],
    'ec794545-ae6f-596b-920d-99a30a5852fb' => [
        'I never thought I was funny, but I enjoy being funny.',
        'Nora Dunn',
    ],
    '8adda55a-e2ce-5c14-aaad-85a4c098b166' => [
        'I was stupid when I started: the epitome of bright-eyed and bushy-tailed. It was like, \'I get to live in L.A. and drive around in limos? Really?\' I didn\'t realize I was owned. The more money gets pumped into you, the more you become a marionette. It made me a true redneck in attitude: I never wanted to wake up ever again feeling owned.',
        'Al Jourgensen',
    ],
    '34786781-3043-5770-b81c-212da480933c' => [
        'A birthday is just another day where you go to work and people give you love. Age is just a state of mind, and you are as old as you think you are. You have to count your blessings and be happy.',
        'Abhishek Bachchan',
    ],
    'c487ce04-b7e5-56b5-b855-9d9c96a30fef' => [
        'All the men in my family were bearded, and most of the women.',
        'W. C. Fields',
    ],
    '69ec3981-b227-5dc8-a864-c5081bb6ded1' => [
        'Inside, I\'ve got a real purist desire and dream about the music. I like the idea of being able to carve out a kind of magical, colourful, artistic, inspirational life. And the reality just turns out to be quite different, working with the business to bring this thing you have created into the world.',
        'Damien Rice',
    ],
    '659226d4-3a00-5095-a23b-075b36616c2f' => [
        'I believe there\'s an inner power that makes winners or losers. And the winners are the ones who really listen to the truth of their hearts.',
        'Sylvester Stallone',
    ],
    '70678915-5e9a-5db7-bceb-2a2da3f11bd4' => [
        'Nothing is a waste of time if you use the experience wisely.',
        'Auguste Rodin',
    ],
    '28ff8ac3-e22b-5969-ba68-5bf8e134bc40' => [
        'The world is getting more connected through technology and travel. Cuisines are evolving. Some people are scared of globalization, but I think people will always take pride in cultural heritage.',
        'John Mackey',
    ],
    'a39a348e-f1fc-5062-9a1d-9d61335e4314' => [
        'Everyone has inside of him a piece of good news. The good news is that you don\'t know how great you can be! How much you can love! What you can accomplish! And what your potential is!',
        'Anne Frank',
    ],
    '978b6eab-883c-5f84-b310-8b091afb8caa' => [
        'I\'ve had a lot of success; I\'ve had failures, so I learn from the failure.',
        'Gordon Ramsay',
    ],
    '5255fb41-c571-5e61-bdd1-eebefa3d3b4f' => [
        'If something stands between you and your success, move it. Never be denied.',
        "Dwayne \u{201c}The Rock\u{201d} Johnson, professional wrestler and actor",
    ],
    '87a5194a-8fe5-5bff-aac6-bdbf6746dd7b' => [
        'Venice is like eating an entire box of chocolate liqueurs in one go.',
        'Truman Capote',
    ],
    '31b296f7-7839-5aa5-a0bc-675b8a196ea2' => [
        'I knew I was an unwanted baby when I saw that my bath toys were a toaster and a radio.',
        'Joan Rivers',
    ],
    '14dedecc-161c-5ad0-870a-63c4266ba029' => [
        'In oneself lies the whole world and if you know how to look and learn, the door is there and the key is in your hand. Nobody on earth can give you either the key or the door to open, except yourself.',
        'Jiddu Krishnamurti',
    ],
    '46f03f7b-afbb-5220-8b91-1e7e4c2f8739' => [
        'May the forces of evil become confused on the way to your house.',
        'George Carlin',
    ],
];
