<?php

return [
    [
        'We know a way now to make use of democracy, and we know how to change the attitude of people towards government, but yet the majority of people are without vision. We who have prevision must lead them and guide them into the right way if we want to escape the confusions of Western democracy and not follow in the tracks of the West.',
        'Sun Yat-sen',
    ],
    [
        'It goes without saying that the Jewish people can have no other goal than Palestine and that, whatever the fate of the proposition may be, our attitude toward the land of our fathers is and shall remain unchangeable.',
        'Theodor Herzl',
    ],
    [
        'The best way to get anybody\'s attention is dinner. I have good kitchen skills and good grocery shopping skills.',
        'Al Roker',
    ],
    [
        'Sometimes words are not needed, and the simplicity of expressing yourself through an art form is one of the best ways of communication.',
        'Emmanuel Jal',
    ],
    [
        'It\'s important to think good, speak good, and do good. If we want to see positive change in the world, then we need to connect to goodness. I try in everything I do, both in business and philanthropy, to make a positive change and do that by doing good.',
        'Shari Arison',
    ],
    [
        'When we run out of them upstairs, I\'ve been known to appropriate some from our greenroom, pocketing a few with one hand as I smile and greet our guests with the other. One time, Dave Zinczenko of \'Eat this, Not That!\' fame, busted me in the act. The cookies apparently fall in the \'not that\' category. I made a note of it.',
        'Lester Holt',
    ],
    [
        'How wonderful that we have met with a paradox. Now we have some hope of making progress.',
        'Niels Bohr',
    ],
    [
        'I just travel the world with my backpack and my cameras and a bunch of Clif bars.',
        'Henry Rollins',
    ],
    [
        'Don\'t listen to what anybody says except the people who encourage you. If it\'s what you want to do and it\'s within yourself, then keep going and try to do it for the rest of your life.',
        'Joseph Campbell',
    ],
    [
        'A beauty is a woman you notice; a charmer is one who notices you.',
        'Adlai E. Stevenson',
    ],
    [
        'You mustn\'t smile when you lose. You have to be sad like other people. You have to win every game.',
        'Eden Hazard',
    ],
    [
        'Having an aim is the key to achieving your best.',
        'Henry J. Kaiser',
    ],
    [
        'Say what you will about the ten commandments, you must always come back to the pleasant fact that there are only ten of them.',
        'H. L. Mencken',
    ],
    [
        'I had rather have a fool to make me merry than experience to make me sad and to travel for it too!',
        'William Shakespeare',
    ],
    [
        'The roots of racism lie deep in man\'s nature, wounded and bruised by original sin.',
        'Sargent Shriver',
    ],
    [
        'When more and more people are thrown out of work, unemployment results.',
        'Calvin Coolidge',
    ],
    [
        'You do manage a somewhat religious attitude toward your art. It is a calling rather than a job.',
        'Jim Harrison',
    ],
    [
        'The more I want to get something done, the less I call it work.',
        'Richard Bach',
    ],
    [
        'Just remember: to be grateful and thank the people who are there and support you along the way is a great start to success.',
        'Meryl Davis',
    ],
    [
        'There\'s certainly an attitude in some measure of the conservative movement that I believe won\'t accept the legitimacy of any Democratic president, and I think Obama did fall victim to that - witness the \'birthers.\'',
        'David Brock',
    ],
    [
        'Never write an advertisement which you wouldn\'t want your family to read. You wouldn\'t tell lies to your own wife. Don\'t tell them to mine.',
        'David Ogilvy',
    ],
    [
        'It is precisely the purpose of the public opinion generated by the press to make the public incapable of judging, to insinuate into it the attitude of someone irresponsible, uninformed.',
        'Walter Benjamin',
    ],
    [
        'Time is what we want most, but what we use worst.',
        'William Penn',
    ],
    [
        'Energy, like the biblical grain of the mustard-seed, will remove mountains.',
        'Hosea Ballou',
    ],
    [
        'It\'s easier to change what you do than people think it is. If you don\'t change, your field changes around you.',
        'Walter Gilbert',
    ],
];
