<?php

return array (
  0 => 
  array (
    0 => 'The past always looks better than it was. It\'s only pleasant because it isn\'t here.',
    1 => 'Finley Peter Dunne (Mr. Dooley)',
  ),
  1 => 
  array (
    0 => 'Nobody who ever gave his best regretted it.',
    1 => 'George Halas',
  ),
  2 => 
  array (
    0 => 'Yes, many primitive people still believe this myth...But in today\'s technical vastness of the future, we can guess that surely things were much different.',
    1 => 'The Firesign Theater',
  ),
  3 => 
  array (
    0 => 'People are crazy and times are strange/ I\'m locked in tight, I\'m out of range/ I used to care, but things have changed.',
    1 => 'Bob Dylan',
  ),
  4 => 
  array (
    0 => 'Without leaps of imagination, or dreaming, we lose the excitement of possibilities. Dreaming, after all, is a form of planning.',
    1 => 'Gloria Steinem',
  ),
  5 => 
  array (
    0 => 'Everybody can be great. Because anybody can serve. You don\'t have to have a college degree to serve. You don\'t have to make your subject and your verb agree to serve.... You don\'t have to know the second theory of thermodynamics in physics to serve. You only need a heart full of grace. A soul generated by love.',
    1 => 'Martin Luther King, Jr.',
  ),
  6 => 
  array (
    0 => 'I\'ve failed over and over and over again. And that is why I succeed.',
    1 => 'Michael Jordan',
  ),
  7 => 
  array (
    0 => 'Tolerance implies a respect for another person, not because he is wrong or even because he is right, but because he is human.',
    1 => 'John Cogley Commonweal',
  ),
  8 => 
  array (
    0 => 'Thoughts become things. If you see it in your mind, you will hold it in your hand.',
    1 => 'Bob Proctor, You Were Born Rich',
  ),
  9 => 
  array (
    0 => 'Just once, I wish we would encounter an alien menace that wasn\'t immune to bullets',
    1 => 'The Brigader, "Dr. Who"',
  ),
  10 => 
  array (
    0 => 'Fear is the main source of superstition, and one of the main sources of cruelty.  To conquer fear is the beginning of wisdom.',
    1 => 'Bertrand Russell',
  ),
  11 => 
  array (
    0 => 'Relativity applies to physics, not ethics.',
    1 => 'Albert Einstein',
  ),
  12 => 
  array (
    0 => 'Those who dream by day are cognizant of many things which escape those who dream only by night.',
    1 => 'Edgar Allen Poe',
  ),
  13 => 
  array (
    0 => 'Success is a journey, not a destination.',
    1 => 'Ben Sweetland',
  ),
  14 => 
  array (
    0 => 'Hitch your wagon to a star.',
    1 => 'Ralph Waldo Emerson',
  ),
  15 => 
  array (
    0 => 'My work is loving the world.',
    1 => 'Mary Oliver',
  ),
  16 => 
  array (
    0 => 'Do whatever you do intensely.',
    1 => 'Robert Henri',
  ),
  17 => 
  array (
    0 => 'We relish news of our heroes, forgetting that we are extraordinary to somebody too.',
    1 => 'Helen Hayes',
  ),
  18 => 
  array (
    0 => 'They alone live, who live for others.',
    1 => 'Swami Vivekananda',
  ),
  19 => 
  array (
    0 => 'Let us realize that: the privilege to work is a gift, the power to work is a blessing, the love of work is success!',
    1 => 'David O. McKay',
  ),
  20 => 
  array (
    0 => 'Success represents the 1% of your work which results from the 99% that is called failure.',
    1 => 'Soichiro Honda',
  ),
  21 => 
  array (
    0 => 'Friendship among nations, as among individuals, calls for constructive efforts to muster the forces of humanity in order that an atmosphere of close understanding and cooperation may be cultivated.',
    1 => 'Franklin D. Roosevelt',
  ),
  22 => 
  array (
    0 => 'Every charitable act is a stepping stone toward heaven.',
    1 => 'Henry Ward Beecher',
  ),
  23 => 
  array (
    0 => 'Once you agree upon the price you and your family must pay for success, it enables you to ignore the minor hurts, the opponent\'s pressure, and the temporary failures.',
    1 => 'Vince Lombardi',
  ),
  24 => 
  array (
    0 => 'Fear is a big liar.',
    1 => 'Robin Sharma',
  ),
);
