<?php

return [
    '8f188e1f-2936-5be5-acc7-4f2cdc00a2d6' => [
        'There is no standing still because time is moving forward.',
        'Greg Lake',
    ],
    '3566e6a1-60c8-5be0-9b5d-172256c6905f' => [
        'Success is the child of drudgery and perseverance. It cannot be coaxed or bribed; pay the price and it is yours.',
        'Orison Swett Marden',
    ],
    '785e4474-0247-5cd1-9b7d-3eb90ea94ae3' => [
        'Talking with my friends and family every day helps keep me grounded and connected to home. They are the most important things to me.',
        'Colbie Caillat',
    ],
    '7017f3bc-dffa-5186-986d-a9db09b64cdc' => [
        'I started modeling when I was - not older, but not 12. I have a mom who\'s a feminist - she\'s an English professor, an intellectual. She really gave me the equipment to understand that you can celebrate yourself without putting yourself down or needing to apologize for the way you look. I think that attitude is really crucial for a model.',
        'Emily Ratajkowski',
    ],
    '0fa14d60-6833-525b-8090-8a9cd777535f' => [
        'Children are the most honest critics. They will say \'You\'re funny\', but also \'You\'re pathetic - go away.\'',
        'Dylan Moran',
    ],
    '0b637b34-1dd2-5275-a066-bdf30046bd64' => [
        'The attitude that poetry should not be analyzed is prevalent among many who consider themselves experts on children\'s literature. But I suspected that kids like to look closely at things and figure out what makes them go.',
        'X. J. Kennedy',
    ],
    '7e25f907-a7d5-57b9-9299-c7d7df922721' => [
        'I think the thing I miss most in our age is our manners. It sounds so old-fashioned in a way. But even bad people had good manners in the old days, and manners hold a community together, and manners hold a family together; in a way, they hold the world together.',
        'Nancy Friday',
    ],
    '8f0d869c-4d68-5410-87bc-f3f54e5960a7' => [
        'If you quit ONCE it becomes a habit.Never quit!!!',
        'Michael Jordan',
    ],
    'd02e075f-2c98-5dce-bdf8-34190a704092' => [
        'The Dolls were an attitude. If nothing else they were a great attitude.',
        'Johnny Thunders',
    ],
    'f86d503e-d0f0-5d2f-8dc2-053d3f582a2a' => [
        'I get asked, \'Who would you really like to work with?\' I\'m already working with them. Smart, talented, funny people, good musicians, an extended family, good friends.',
        'Christopher Guest',
    ],
    '755a7d64-107d-5ba5-896b-7179e07f2727' => [
        'If you manifest your true self through nature and your normal surroundings, I find that the most eerie. Like when you see birds suddenly start flying in a different direction or when you see moths forming weird shapes, I think that\'s the weirdest way to let yourself be known.',
        'Holland Roden',
    ],
    'c3aafae8-87df-5819-9c8d-1b075d8ce8a6' => [
        'Occasionally I have come across a last patch of snow on top of a mountain in late May or June. There\'s something very powerful about finding snow in summer.',
        'Andy Goldsworthy',
    ],
    '23862304-123c-53d0-8b29-9fecb0983858' => [
        'The only difference between death and taxes is that death doesn\'t get worse every time Congress meets.',
        'Will Rogers',
    ],
    'e4871fac-db1a-50c5-8de4-b29f2c4eaacb' => [
        'Beauty, to me is about being comfortable in your own skin.',
        'Gwyneth Paltrow',
    ],
    'c47976f5-3ed6-5dbb-aa2a-3c61b23ab1fc' => [
        'I have now disposed of all my property to my family. There is one thing more I wish I could give them, and that is the Christian religion.',
        'Patrick Henry',
    ],
    '93d97ca0-5296-5624-8064-7451d7773e35' => [
        'It is precisely the purpose of the public opinion generated by the press to make the public incapable of judging, to insinuate into it the attitude of someone irresponsible, uninformed.',
        'Walter Benjamin',
    ],
    'c57857e8-7c2f-5011-9995-35e14acf4fcf' => [
        'Maybe that is why kids like Dumbledore: because he is funny rather than a miserable old sod with a long white beard.',
        'Michael Gambon',
    ],
    '6b5b8d60-5f71-5bc5-95b6-d2e1aaa357fb' => [
        'I work a lot of hours, and in this business you really try to keep as busy as you possibly can. Sometimes when you really focus on kids in your free time you lose the husband and wife relationship to some degree. It\'s been a real focus for us to make sure we stay focused on us two.',
        'Cameron Mathison',
    ],
    '2b8869fc-4094-5a88-a6e4-a152570c9435' => [
        'Beginning today, treat everyone you meet as if they were going to be dead by midnight. Extend to them all the care, kindness and understanding you can muster, and do it with no thought of any reward. Your life will never be the same again.',
        'Og Mandino',
    ],
    'b37983ca-80a5-5a32-bd01-d15ee54466e3' => [
        'It is not the language of painters but the language of nature which one should listen to, the feeling for the things themselves, for reality is more important than the feeling for pictures.',
        'Vincent Van Gogh',
    ],
    '0e481ffd-fd8f-5bab-8f03-3a46469caaf0' => [
        'To be successful in coaching you have to treat your team like a family. The leader needs backing from everyone.',
        'Morgan Wootten',
    ],
    'bde88ed7-3df8-524f-9a7c-06dbd228088b' => [
        'All I know is it destroyed my family, it destroyed my marriage to Sylvester and I will never get over it.',
        'Brigitte Nielsen',
    ],
    '9dbb3c68-ead6-556f-bdef-e2eea6db2265' => [
        'I am a Piscean, and they have a lovingly detached attitude towards life.',
        'Shahid Kapoor',
    ],
    '037ebc50-75de-563e-b6ff-65d7d56066c8' => [
        'Instead of drifting along like a leaf in a river, understand who you are and how you come across to people and what kind of an impact you have on the people around you and the community around you and the world, so that when you go out, you can feel you have made a positive difference.',
        'Jane Fonda',
    ],
    '52d0e0e5-bc5d-52b8-be0b-47ba834afb5d' => [
        'When the sun is shining I can do anything; no mountain is too high, no trouble too difficult to overcome.',
        'Wilma Rudolph',
    ],
    '1ea9f27f-dd8e-564b-9483-379377926f49' => [
        'My journey has been a very fun one because I\'ve chosen to make the best of every challenge that I\'ve had along the way no matter what.',
        'Ciara',
    ],
    '44fa72f1-0a84-55f3-8161-a5cc388cf062' => [
        'To do all that one is able to do, is to be a man; to do all that one would like to do, is to be a god.',
        'Napoleon Bonaparte',
    ],
    '83263564-750a-5b7f-98a3-41ad9fd43e5b' => [
        'We see things not as they are, but as we are. Our perception is shaped by our previous experiences.',
        'Dennis Kimbro',
    ],
    'b6c99a04-86fc-539a-9f75-2bea947a2f81' => [
        'I\'m passionate and I travel the world not just as a tourist but to understand cultures... I\'ve lived with Masai tribe... I travel the world and bring it back in the form of a research book that would become the starting point for the collection.',
        'John Galliano',
    ],
    'b4e54c1c-f3a6-505f-ad16-b64f409e0048' => [
        'Staying in one place is the best path to be taken over and surpassed by many.',
        'Byron Pulsifer',
    ],
    'c80e4dee-614e-567a-9e04-b193d61c1f21' => [
        'By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day.',
        'Robert Frost',
    ],
    '079599a3-2ce9-5a43-b3df-f8fa08bafffc' => [
        'The artist is not responsible to any one. His social role is asocial... his only responsibility consists in an attitude to the work he does.',
        'Georg Baselitz',
    ],
    '6b1affef-9707-5f78-8fb0-b12c1c179587' => [
        'A warm smile is the universal language of kindness.',
        'William Arthur Ward',
    ],
    'ee5052dd-add5-5865-9e9b-87f9a132750e' => [
        'The truth which has made us free will in the end make us glad also.',
        'Felix Adler',
    ],
    '388f16b1-84a8-590c-9a32-543eacc9aba9' => [
        'I was walking around legally blind. Now I have 20-20 vision. I can\'t believe I spent so many years blurry, but I think that coincides with how I was feeling. Now I notice if people are watching me, but I also smile right back if someone waves, which helps.',
        'Nicole Kidman',
    ],
    'f7cd0841-b1bb-5c5c-ad10-dba3cea62496' => [
        'I take work very seriously and telling the truth in my job and professionalism.',
        'Brittany Murphy',
    ],
    '8d71a830-9f24-5eb2-ad81-62ffb49d5c61' => [
        'I love Rauschenberg. I love that he created a turning point in visual history, that he redefined the idea of beauty, that he combined painting, sculpture, photography, and everyday life with such gall, and that he was interested in, as he put it, \'the ability to conceive failure as progress.\'',
        'Jerry Saltz',
    ],
    '116f368f-1e61-540d-b262-93bf8aa8d765' => [
        'I grew up in an era of thinking of travel as escape. The idea that you could conceivably have a new life, go somewhere, fall in love, have little children under the palm trees.',
        'Paul Theroux',
    ],
    '660633b9-d351-5f16-bf01-d374e2bfa040' => [
        'Publishers like a good buzz, and negative responses sell books just as well as positive ones.',
        'Richard Dawkins',
    ],
    '34883812-8907-5d42-9da5-c8757af328d2' => [
        'Walk on a rainbow trail; walk on a trail of song, and all about you will be beauty. There is a way out of every dark mist, over a rainbow trail.',
        'Robert Motherwell',
    ],
    '81397494-ab82-5bf4-b6e1-03577ea40f3e' => [
        'Just as the left has to be more willing to question \'Government knows best,\' the right has to rethink its laissez-faire attitude toward government.',
        'Jack Kemp',
    ],
    '73e7ba7d-a147-5980-b825-b72873b91e2a' => [
        'Personal relationships are the fertile soil from which all advancement, all success, all achievement in real life grows.',
        'Ben Stein',
    ],
    '9f13802c-a56c-5a75-b7c6-291d8b3be844' => [
        'I\'ve been fascinated by the Internet from the very start. In 2001, I had made a funny black-and-white film called \'How to Dance Properly,\' a short video of me dancing to a Madonna song. I sent it to 17 of my friends on a Thursday, and by Monday, one million people a day were logging on to view it.',
        'Ze Frank',
    ],
    '418e9e28-9c6c-5602-80c3-4511b04272ab' => [
        'Marriage is a wonderful institution, but who would want to live in an institution?',
        'H. L. Mencken',
    ],
    'ea8be603-b9fa-5efd-a519-4e51656546a6' => [
        'I was brought up by a single mom in a poor town in Arkansas and while some aspects of small-town life were really positive - like the fact that everyone there is really sweet and hospitable - there is also this close-minded mentality, and that naturally made me want to rebel.',
        'Beth Ditto',
    ],
    'eef38b6b-52d3-52bb-ba50-9f60173046e6' => [
        'I\'ve reached a point in my life where it\'s the little things that matter... I was always a rebel and probably could have got much farther had I changed my attitude. But when you think about it, I got pretty far without changing attitudes. I\'m happier with that.',
        'Veronica Lake',
    ],
    '4e4ac83f-42c4-5a37-8725-e55481796933' => [
        'If ants are such busy workers, how come they find time to go to all the picnics?',
        'Marie Dressler',
    ],
    '57fefdf3-5467-5edc-a228-00e18b2d9f6c' => [
        'When asked, \'How do you write?\' I invariably answer, \'one word at a time.\'',
        'Stephen King',
    ],
    '42afad32-4954-541b-a8c0-a7d4fa5e7a18' => [
        'Include me out.',
        'Samuel Goldwyn',
    ],
    '947fd598-97e5-536f-80a1-66a38b983e86' => [
        'Knowledge has three degrees, opinion, science, illumination. The means or instrument of the first is sense; of the second, dialectic; of the third, intuition.',
        'Plotinus',
    ],
];
