<?php

return [
    [
        'When I had money in the past, I would always travel rather than spend it on big apartments or cars. And I still feel exactly the same way.',
        'Robin Wright',
    ],
    [
        'No fine work can be done without concentration and self-sacrifice and toil and doubt.',
        'Max Beerbohm',
    ],
    [
        'I have no regrets, because I\'ve done everything I could to the best of my ability.',
        'Robert Redford',
    ],
    [
        'Humanism was not wrong in thinking that truth, beauty, liberty, and equality are of infinite value, but in thinking that man can get them for himself without grace.',
        'Simone Weil',
    ],
    [
        'A work of art when placed in a gallery loses its charge, and becomes a portable object or surface disengaged from the outside world.',
        'Robert Smithson',
    ],
    [
        'There is no end of craving. Hence contentment alone is the best way to happiness. Therefore, acquire contentment.',
        'Swami Sivananda',
    ],
    [
        'Instead of this confusion, we need the unifying force of an official language, English, which is the language of success in America.',
        'Ernest Istook',
    ],
    [
        'I\'m different, and I have to be a warrior to be that way. But I have had some success; I hope I have touched the lives of some wonderful people, all by being what I see as myself but some others people see as different.',
        'Johnny Weir',
    ],
    [
        'I do love to capture beauty in this world. And photos can last the test of time.',
        'Nathaniel Buzolic',
    ],
    [
        'Motivation is everything. You can do the work of two people, but you can\'t be two people. Instead, you have to inspire the next guy down the line and get him to inspire his people.',
        'Lee Iacocca',
    ],
    [
        'I have to stay alone in order to fully contemplate and feel nature.',
        'Caspar David Friedrich',
    ],
    [
        'Believe in yourself, and the rest will fall into place. Have faith in your own abilities, work hard, and there is nothing you cannot accomplish.',
        'Brad Henry',
    ],
    [
        'The boundaries which divide Life from Death are at best shadowy and vague. Who shall say where the one ends, and where the other begins?',
        'A. P. J. Abdul Kalam',
    ],
    [
        'We need to give each other the space to grow, to be ourselves, to exercise our diversity. We need to give each other space so that we may both give and receive such beautiful things as ideas, openness, dignity, joy, healing, and inclusion.',
        'Anne Roiphe',
    ],
    [
        'Absence makes the heart grow fonder.',
        'Haynes Bayly',
    ],
    [
        'With every drop of water you drink, every breath you take, you\'re connected to the sea. No matter where on Earth you live. Most of the oxygen in the atmosphere is generated by the sea.',
        'Sylvia Earle',
    ],
    [
        'Self-trust is the first secret of success.',
        'Ralph Emerson',
    ],
    [
        'I do think that travel can be part of a journey of inner maturation, but you\'ve got to do it right.',
        'Alain de Botton',
    ],
    [
        'I don\'t want just attitude and loud opinion.',
        'John McLaughlin',
    ],
    [
        'When you retire, it\'s a place in life, a part of the journey. You just don\'t quit work; you develop an attitude where you can do what you please.',
        'Tom T. Hall',
    ],
    [
        'I think it\'s a comedian\'s job to make everything funny. Nothing is off-limits.',
        'Donald Glover',
    ],
    [
        'Being an astronaut is a wonderful career. I feel very privileged. But what I really hope for young people is that they find a career they\'re passionate about, something that\'s challenging and worthwhile.',
        'Ellen Ochoa',
    ],
    [
        'Comfort is the enemy of achievement.',
        'Farrah Gray',
    ],
    [
        'Some people say they have a thirst for life. They\'re excited about every day and they\'re prepared to look the bad and the good straight in the face and greet it all with a smile. I like to think I\'m one of those people.',
        'Amy Jo Martin',
    ],
    [
        'Let us always meet each other with smile, for the smile is the beginning of love.',
        'Mother Teresa',
    ],
];
