<?php

return [
    '34541b35-fdff-5650-8074-edf865367aa3' => [
        'The decisions you make are a choice of values that reflect your life in every way.',
        'Ernest Hemingway',
    ],
    '7e8462f7-101e-50fc-8e43-994c94a91c15' => [
        'You want everyone to be great and funny. I\'m not saying I\'m great, but I\'m funny.',
        'Jon Lovitz',
    ],
    '1f6acd56-242a-5c11-b039-0f47b234f384' => [
        'If you can\'t explain it simply, you don\'t understand it well enough.',
        'Albert Einstein',
    ],
    '1c02ecbb-6d1f-5310-ab2d-4d422ee30c07' => [
        'I\'ve done so much travelling in the past few years, and when you travel, you realise that we do actually have a cool, clean look in Scandinavia - it\'s not just Denmark - which I think brings peace if you have it in your home.',
        'Birgitte Hjort Sorensen',
    ],
    'cf17af0a-1568-5bff-833b-972e05aa6f7a' => [
        'The major work of the world is not done by geniuses. It is done by ordinary people, with balance in their lives, who have learned to work in an extraordinary manner.',
        'Gordon B. Hinckley',
    ],
    'c05f531c-6b40-5e41-b7de-e8fe282ce5bf' => [
        'Relax! Life is beautiful!',
        'Marvin Sapp',
    ],
    'ce3385de-50c5-5a85-a470-bd4e74cdfa04' => [
        'The breaks you take from work pay you back manifold when you return because you come back with a fresher mind and newer thinking. Some of your best ideas come when you\'re on vacation.',
        'Gautam Singhania',
    ],
    'f6cdfb99-d73d-5f45-a69b-2c4afd66ae06' => [
        'I began making pictures because I wanted to record what supports hope: the untranslatable mystery and beauty of the world. Along the way, however, the camera also caught evidence against hope, and I eventually concluded that this, too, belonged in pictures if they were to be truthful and thus useful.',
        'Robert Adams',
    ],
    '8f6b2328-15a9-5f9e-889a-4742d5bf8e8c' => [
        'Poetry, at its best, is the language your soul would speak if you could teach your soul to speak.',
        'Jim Harrison',
    ],
    '217355cf-76d7-5f93-8690-dac0f3db0e7f' => [
        'Hurried and worried until we\'re buried, and there\'s no curtain call, Lifes a very funny proposition after all.',
        'George M. Cohan',
    ],
    '27d1021b-99cc-59a6-be2e-e6d94115ff19' => [
        'With every drop of water you drink, every breath you take, you\'re connected to the sea. No matter where on Earth you live. Most of the oxygen in the atmosphere is generated by the sea.',
        'Sylvia Earle',
    ],
    '2fb1fd4e-4e7d-5b84-81a1-09e7d11ff3ee' => [
        'Italians come to ruin most generally in three ways, women, gambling, and farming. My family chose the slowest one.',
        'Pope John XXIII',
    ],
    '9a933d1c-9937-506b-a0ba-59d0bbdcfed9' => [
        'I think for any small business that\'s bootstrapped, the overwhelming challenge initially is getting to positive cash flow.',
        'John Mackey',
    ],
    'bdebcec8-1e5e-509d-9d9b-aa563ed60296' => [
        'Only those who dare to fail greatly can ever achieve greatly.',
        'Robert Kennedy',
    ],
    '2de3f891-9d23-5398-bae2-fb026f0bceac' => [
        'In every battle there comes a time when both sides consider themselves beaten, then he who continues the attack wins.',
        'Ulysses S. Grant',
    ],
    'f5668910-551f-5542-957e-566000c4d45c' => [
        'All you need in this life is ignorance and confidence, and then success is sure.',
        'Mark Twain',
    ],
    'f6173d6f-0456-5359-94c5-56259fe7f475' => [
        'Education is the key to success in life, and teachers make a lasting impact in the lives of their students.',
        'Solomon Ortiz',
    ],
    '3bd92100-8599-5b13-868e-7ef7a49ef394' => [
        'I truly believe in positive synergy, that your positive mindset gives you a more hopeful outlook, and belief that you can do something great means you will do something great.',
        'Russell Wilson',
    ],
    'caa21bcc-e6a4-51e7-87ec-48f0739a278f' => [
        'You do not pay the price of success, you enjoy the price of success.',
        'Zig Ziglar',
    ],
    '2ce39b60-b528-595d-801e-c2345319865b' => [
        'If you want to achieve greatness stop asking for permission.',
        'Unknown',
    ],
    'c1bf55e0-8b1c-544e-8e96-fde2bff855fb' => [
        'Even as a kid I was never the generator of humor, but I always knew who was funny, who to hang out with.',
        'Andrew Stanton',
    ],
    'bf59a24e-3d21-5754-94a7-30ab9870e5a4' => [
        'If you have no respect for your own values how can you be worthy of respect from others.',
        'Byron Pulsifer',
    ],
    'de8f6005-5aed-56c8-ac5a-bb65322d6b70' => [
        'What I would say to young entrepreneurs is there\'s so many moments in your life where you have these dreams, and people are trying to protect you, and they say, perhaps, friends, family, parents sometimes, they don\'t agree with it, they think, \'This is just too high of a hurdle.\' And I don\'t agree with that.',
        'Howard Schultz',
    ],
    '5f807e6e-85ac-51c5-9398-7c3ee74e9d79' => [
        'Success is nothing if you don\'t have the right people to share it with; you\'re just gonna end up lonely.',
        'Selena Gomez',
    ],
    'cabe8382-4a14-5e44-a5ac-5bc99a632d91' => [
        'Financial institutions, the corporate world and civil society - all must uphold high standards of probity in their working. Only a genuine partnership between the Government and its people can bring about positive change to create a just society.',
        'Pratibha Patil',
    ],
];
