<?php

return [
    [
        'The person who lives life fully, glowing with life\'s energy, is the person who lives a successful life.',
        'Daisaku Ikeda',
    ],
    [
        'Success is following the pattern of life one enjoys most.',
        'Al Capp',
    ],
    [
        'If I went to them all dressed up and flashed a nice smile for the cameras it would probably be easier for me to get work. But I just can\'t tolerate it.',
        'Charlie Hunnam',
    ],
    [
        'Moments of complete apathy are the best for new creations.',
        'Philip Breedveld',
    ],
    [
        'Big shots are only little shots who keep shooting.',
        'Christopher Morley',
    ],
    [
        'Power is, in its nature, encroaching; and such is the human make that men who are vested with a share of it are generally inclined to take more than it was intended they should have.',
        'Samuel Adams',
    ],
    [
        'I work very hard, and I play very hard. I\'m grateful for life. And I live it - I believe life loves the liver of it. I live it.',
        'Maya Angelou',
    ],
    [
        'I\'d never stop traveling, and I love bringing my family along with me. My children have points of reference everywhere, friends from Milan to Los Angeles. I think it\'s really fun for them.',
        'Valeria Mazza',
    ],
    [
        'I will not be concerned at other men is not knowing me;I will be concerned at my own want of ability.',
        'Confucius',
    ],
    [
        'Time is but the stream I go a-fishing in.',
        'Henry David Thoreau',
    ],
    [
        'The deepest craving of human nature is the need to be appreciated.',
        'William James',
    ],
    [
        'Ours is the century of enforced travel of disappearances. The century of people helplessly seeing others, who were close to them, disappear over the horizon.',
        'John Berger',
    ],
    [
        'I wish that the Indians believed me a god, for upon the report of an enemy\'s valor oftentimes depends the success of a battle, and false reports have many times done as great things as true courage and resolution.',
        'Alexander the Great',
    ],
    [
        'Knowledge is going to make you stronger. Knowledge is going to let you control your life. Knowledge is going to give you the wisdom to teach their children. Knowledge is the thing that makes you smile in the face of disaster.',
        'Avery Brooks',
    ],
    [
        'The limits of sensory evolution in fish are defined very largely by their habitat. Water is physically supportive, carries some kinds of odour well, and is kind to sound - letting it travel several times faster than air will allow, but it inhibits other more personal kinds of communication.',
        'Lyall Watson',
    ],
    [
        'Edison failed 10,000 times before he made the electric light. Do not be discouraged if you fail a few times.',
        'Napoleon Hill',
    ],
    [
        'The real business of life is trying to understand each other.',
        'Plato',
    ],
    [
        'I smile so much at the theater my face hurts when I leave.',
        'Heather Matarazzo',
    ],
    [
        'If I hadn\'t spent many years trying to be as compassionate as Mother Teresa, as positive a thinker as W. Clement Stone, as prolific a writer as Stephen King, and as good a speaker as many of the legends I have studied, I would not be as successful as I am today.',
        'Jack Canfield',
    ],
    [
        'Sometimes you\'re not even sure which of your stories were failures. There are things I\'ve written that I thought were complete catastrophes when I finished with them that have gone on to generate some of my most positive feedback.',
        'Len Wein',
    ],
    [
        'The whole notion of pain, and how every individual experiences pain, is up for debate. We don\'t know how another person experiences pain - physical pain or psychic pain. Some of these clinics where assisted suicide or euthanasia is practiced, they call it \'weariness of life.\'',
        'Shemar Moore',
    ],
    [
        'So during those first moments of the day, which are yours and yours alone, you can circumvent these boundaries and concentrate fully on spiritual matters. And this gives you the opportunity to plan the time management of the entire day.',
        'Menachem Mendel Schneerson',
    ],
    [
        'Reggae has a philosophy, you know? It\'s not just entertainment. There\'s an idea behind it, a way of life behind the music, which is a positive way of life, which is a progressive way of life for better people.',
        'Ziggy Marley',
    ],
    [
        'It is precisely the purpose of the public opinion generated by the press to make the public incapable of judging, to insinuate into it the attitude of someone irresponsible, uninformed.',
        'Walter Benjamin',
    ],
    [
        'And I\'m a believer that you take a negative and turn it into a positive, and as it turned out, it was one of the best things that ever happened to me. And so I do appreciate the Ranger staff and the Ranger organization for giving me that opportunity.',
        'Nolan Ryan',
    ],
];
