<?php

return [
    [
        'I was successful materially, but I know life is much more than worldly success. I saw all these blessings God had given me. The way to give thanks is obedience to God.',
        'Hakeem Olajuwon',
    ],
    [
        'Painting is by nature a luminous language.',
        'Robert Delaunay',
    ],
    [
        'I live in a town called Beerwah, right in the middle of Australia Zoo. It\'s not hustle and bustle and busy, so that\'s helpful. We travel all over the world, but I\'ve always been able to come home and run around in the middle of the Australian outback.',
        'Bindi Irwin',
    ],
    [
        'With every drop of water you drink, every breath you take, you\'re connected to the sea. No matter where on Earth you live. Most of the oxygen in the atmosphere is generated by the sea.',
        'Sylvia Earle',
    ],
    [
        'Work is that which you dislike doing but perform for the sake of external rewards. At school, this takes the form of grades. In society, it means money, status, privilege.',
        'Abraham Maslow',
    ],
    [
        'I knew from the first moment I picked up a camera, on my first school assignment, what I wanted to do for the rest of my life. I was going to find a way to travel the world and tell the stories of the people I met through photographs.',
        'Mary Ellen Mark',
    ],
    [
        'Life is short and if you\'re looking for extension, you had best do well. \'Cause there\'s good deeds and then there\'s good intentions. They are as far apart as Heaven and Hell.',
        'Ben Harper',
    ],
    [
        'Where there is great love, there are always miracles.',
        'Willa Cather',
    ],
    [
        'Love is our true destiny. We do not find the meaning of life by ourselves alone - we find it with another.',
        'Christopher Reeve',
    ],
    [
        'We have to remember that Putin was a member of the KGB. He has already demonstrated that kind of macho, dictatorial attitude. Russia has breached their pledge to uphold the Olympic charter. This is a great opportunity for the IOC to say we cannot, given the situation that exists currently, allow the Olympics to take place in Russia.',
        'George Takei',
    ],
    [
        'Believe you can and you\'re halfway there.',
        'Theodore Roosevelt',
    ],
    [
        'To live is so startling it leaves little time for anything else.',
        'Keanu Reeves',
    ],
    [
        'Let us always meet each other with smile, for the smile is the beginning of love.',
        'Mother Teresa',
    ],
    [
        'I like to help kids, work with kids in detention homes. Don\'t tell a kid what\'s right and wrong. He knows what\'s right and wrong. Find out what his attitude and his aptitude are; try to help him where he wants to go.',
        'Evel Knievel',
    ],
    [
        'At the end of the day, you are solely responsible for your success and your failure. And the sooner you realize that, you accept that, and integrate that into your work ethic, you will start being successful. As long as you blame others for the reason you aren\'t where you want to be, you will always be a failure.',
        'Erin Cummings',
    ],
    [
        'We have one planet in our solar system that\'s habitable, and that\'s the Earth, and space travel can transform things back here for the better. First of all, by just having people go to space and look back on this fragile planet we live on. People have come back transformed and have done fantastic things.',
        'Richard Branson',
    ],
    [
        'If you can\'t be in awe of Mother Nature, there\'s something wrong with you.',
        'Alex Trebek',
    ],
    [
        'Neither man nor woman is perfect or complete without the other. Thus, no marriage or family, no ward or stake is likely to reach its full potential until husbands and wives, mothers and fathers, men and women work together in unity of purpose, respecting and relying upon each other\'s strengths.',
        'Sheri L. Dew',
    ],
    [
        'Funny is funny.',
        'Don Rickles',
    ],
    [
        'I think hearts are very much like glasses. If they do not break with the first ring, they usually last a considerable time.',
        'Letitia Elizabeth Landon',
    ],
    [
        'I am a generous man, by nature, and far more trusting than I should be. Indeed. The real world is risky territory for people with generosity of spirit. Beware.',
        'Hunter S. Thompson',
    ],
    [
        'The equal right of all citizens to health, education, work, food, security, culture, science, and wellbeing - that is, the same rights we proclaimed when we began our struggle, in addition to those which emerge from our dreams of justice and equality for all inhabitants of our world - is what I wish for all.',
        'Fidel Castro',
    ],
    [
        'Reject your sense of injury and the injury itself disappears.',
        'Marcus Aurelius',
    ],
    [
        'Positive thinking is the key to success in business, education, pro football, anything that you can mention. I go out there thinking that I\'m going to complete every pass.',
        'Ron Jaworski',
    ],
    [
        'Stop being afraid of what could go wrong, and start being excited about what could go right.',
        'Unknown',
    ],
];
